package DataMiningLogHistoriKIRIWithoutDateAndMinutes;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Jovan Gunawan
 */
public class View extends javax.swing.JPanel {

    /**
     * Creates new form View
     */
    public View(Controller cont) {
        this.cont = cont;
        initComponents();
        buttonGroup1.add(radioButtonId3);
        buttonGroup1.add(radioButtonJ48);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        judul = new javax.swing.JLabel();
        labelFileData = new javax.swing.JLabel();
        labelPemilihanMethod = new javax.swing.JLabel();
        radioButtonId3 = new javax.swing.JRadioButton();
        radioButtonJ48 = new javax.swing.JRadioButton();
        textFieldFilePath = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        labelHasil = new javax.swing.JLabel();
        buttonBrowse = new javax.swing.JButton();
        labelKeterangan = new javax.swing.JLabel();

        judul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judul.setText("Data Mining Log Histori KIRI");

        labelFileData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFileData.setText("File Data (CSV):");

        labelPemilihanMethod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelPemilihanMethod.setText("Metode Pembuatan Tree:");

        radioButtonId3.setSelected(true);
        radioButtonId3.setText("ID3");

        radioButtonJ48.setText("J48");
        radioButtonJ48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonJ48ActionPerformed(evt);
            }
        });

        buttonStart.setText("Start!");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        hasil.setColumns(20);
        hasil.setRows(5);
        scrollPanel.setViewportView(hasil);

        labelHasil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelHasil.setText("Hasil:");

        buttonBrowse.setText("Browse");
        buttonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrowseActionPerformed(evt);
            }
        });

        labelKeterangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFileData, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBrowse))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelPemilihanMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioButtonId3)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioButtonJ48))
                                    .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                                    .addComponent(labelKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFileData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPemilihanMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonJ48)
                    .addComponent(radioButtonId3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(scrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(labelKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrowseActionPerformed
        final JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(buttonStart);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            textFieldFilePath.setText(file.getPath());
        } else {
            System.out.println("Error in capture the path");
            System.exit(1);
        }
    }//GEN-LAST:event_buttonBrowseActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        String inputPath = textFieldFilePath.getText();
        String miningAlgo = "";
        if(radioButtonId3.isSelected())
        {
            miningAlgo = "id3";
        }
        else
        {
            miningAlgo = "j48";
        }
        
        try {
            cont.startMining(inputPath, miningAlgo, labelKeterangan, hasil);
        }catch(IOException e)
        {
            System.out.println("Error start mining");
            System.exit(1);
        }
    }//GEN-LAST:event_buttonStartActionPerformed

    private void radioButtonJ48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonJ48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonJ48ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonStart;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labelFileData;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel labelPemilihanMethod;
    private javax.swing.JRadioButton radioButtonId3;
    private javax.swing.JRadioButton radioButtonJ48;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTextField textFieldFilePath;
    // End of variables declaration//GEN-END:variables
    private Controller cont;
}
